---
title: "Univariate MR of mediators to BC"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(data.table)
library(vroom)

library(tidyr)
library(purrr)
library(tibble)
library(dplyr)

library(TwoSampleMR)
library(ggplot2)
library(cowplot)
library(wesanderson)
```

```{r message=F}
# set path for pre-calculated data, outside the code repo
# `local` / `remote` (reading data from RDSF)
currently_working_env = "local"
source("set_paths.R")
set_paths(currently_working_env)

# metafile
data_lookup<-read_csv(paste0("metadata/data_lookup.csv")) 
bcac_lookup<-read_csv(paste0("metadata/data_lookup_BCAC.csv")) 

# load functions
source("functions.R")
```


```{r}
# specify group to process if data is in textfiles
source = "textfiles"
current_trait_category <- "md_wo_outliers"
mediators <- data_lookup %>% filter(trait_category == current_trait_category) %>% filter(!is.na(full_data)) %>%  pull(tophits_data)

# specify group to process  if the data is in MRBase
#source = "mrbase"
#current_trait_category <- ".."
#mediators <- data_lookup %>% filter(trait_category == current_trait_category) %>% filter(!is.na(mrbase.id)) %>%  pull(mrbase.id)

```


## Reading in / extracting instruments
```{r}
if (source == "textfiles"){
  
    data_list <- lapply(paste0(data_path_tophits, mediators), fread)
    
} else if (source == "mrbase"){

  data_list <- list()
  for (i in 1:length(mediators)){
    instruments <- extract_instruments(mediators[i])
    if (is.null(instruments)){ stop(paste0("No instruments found for ", mediators[i]))} # if no SNPs returned
    data_list[[i]] <- clump_data(instruments)
    data_list[[i]]$exposure <- data_lookup %>% filter(mrbase.id==mediators[i]) %>% pull(trait)
  }
}
```




```{r message=F, warning=F}

extract_outcome_data_custom <- function(exposure_dat, breast_cancer_data, outcome_source){
  # function to extract instrument from a specified outcome
  
  if (outcome_source == "outcome_textfile"){
    out <- breast_cancer_data %>%
              filter(SNP %in% exposure_dat$SNP)
    
  } else if (outcome_source == "outcome_mrbase"){
  
    out <- extract_outcome_data(
              snps = exposure_dat$SNP,
              outcome = breast_cancer_data) 
  }
  return(out)
}
```


```{r}
# This for loop will iterate over all breast cancer outcomes and do all steps of MR

for (i in 1:length(bcac_lookup$trait)){

  if (!is.na(bcac_lookup$mr.base.id[i])){
    outcome_source = 'outcome_mrbase'
    outcome_name = bcac_lookup$mr.base.id[i]
    print(paste0( "Testing all mediators against breast cancer data: ", outcome_name))
    breast_cancer_data <- outcome_name
  } else {
    outcome_source = 'outcome_textfile'
    outcome_name = bcac_lookup$full_data[i]
    print(paste0( "Testing all mediators against breast cancer data: ", outcome_name))
    # read in the outcome file
    breast_cancer_data  <- vroom(paste0(data_path_gwas, outcome_name)) 
  }
  outcome_trait_name = bcac_lookup$trait_file_name[i]

  outcomes <- lapply(data_list, extract_outcome_data_custom, breast_cancer_data, outcome_source)
  
  # check how many SNPs are present in the outcome
  for (i in 1:length(data_list)){
    print(unique(data_list[[i]]$exposure))
    print(paste0("SNPs in exposure: ", dim(data_list[[i]])[1]))
    print(paste0("SNPs matches outcome: ", dim(outcomes[[i]])[1]))
  }
  
  # Harmonise each exposure to the matched outcome SNPs
  harmonise_l <- list()
  for (i in 1:length(data_list)){
     harmonise_l[[i]] <- harmonise_data(exposure_dat = data_list[[i]], 
                                        outcome_dat = outcomes[[i]])
  }
  
  # Pleiotropy and Heterogeneity
  sensitivity_l <- list()
  for (i in 1:length(harmonise_l)){
    # don't try it one 1-SNP cases
    if (dim(harmonise_l[[i]])[1] != 1){
    sensitivity_l[[i]] <- full_join(
                          mr_pleiotropy_test(harmonise_l[[i]]),
                          mr_heterogeneity(harmonise_l[[i]], method_list=c("mr_egger_regression", "mr_ivw"))
                          )
    }
  }   
    
  # perform MR
  mr_l <- list()
  for (i in 1:length(harmonise_l)){
    mr_l[[i]] <- mr(harmonise_l[[i]],  method_list=c('mr_ivw','mr_egger_regression','mr_weighted_median', 'mr_wald_ratio') ) 
  }
  
  
  ## Tidy up results 
  #  - Split outcome names
  #  - Generate odds ratios with 95% confidence intervals
    
  tidy_result_l <- list()
  for (i in 1:length(mr_l)){
    tidy_result_l[[i]] <- mr_l[[i]] %>%
                          split_outcome() %>% 
                          split_exposure() %>% 
                          separate(outcome, "outcome", sep="[(]") %>% 
                          generate_odds_ratios()
  }
  
  dat <- tidy_result_l %>%
        reduce(rbind) %>% 
        arrange(method) %>% 
        select(-c("id.exposure")) 
  
  # save full data from MR analyses
  ind_res_dir <- paste0(results_path, current_trait_category, "/")
  ind_res_dir_w_backslash <- gsub(" ", "\\ ", ind_res_dir, fixed=T) # create path vector escaping spaces, otherwise sytem call cant process it
  if(!dir.exists(ind_res_dir)){ system(paste("mkdir -p", ind_res_dir_w_backslash))}
  
  
  write_tsv(dat, paste0(ind_res_dir,"merged_mr_mediators_", current_trait_category,"-to-BCAC_", outcome_trait_name,".tsv"))
  
  
  dat_sensitivity <- sensitivity_l %>%
        reduce(rbind) %>% 
        split_outcome() %>%
        separate(outcome, "outcome", sep="[(]") %>% 
        select(-c("id.exposure", "id.outcome")) 
  
  # save sensitivity analyses results
  write_tsv(dat_sensitivity, paste0(ind_res_dir,"merged_sens_mr_mediators_", current_trait_category,"-to-BCAC_", outcome_trait_name,".tsv"))
  
}
```

# TESTING
```{r}
da_old <- read_tsv(paste0(data_path_tophits, "mammographic_density_DA_sieh_tophits.tsv")) #16
nda_old <- read_tsv(paste0(data_path_tophits, "mammographic_density_NDA_sieh_tophits.tsv")) # 11
pd_old <- read_tsv(paste0(data_path_tophits, "mammographic_density_PD_sieh_tophits.tsv")) # 10
                   

da_new <- read_tsv(paste0(data_path_tophits, "dense_area_tophits.tsv")) # 25
nda_new <- read_tsv(paste0(data_path_tophits, "nondense_area_tophits.tsv")) # 16
pd_new <- read_tsv(paste0(data_path_tophits, "percent_density_tophits.tsv")) # 16


length(intersect(da_old$SNP , da_new$SNP)) # 15
length(intersect(nda_old$SNP , nda_new$SNP)) #11
length(intersect(pd_old$SNP , pd_new$SNP)) # 9



md_gwas_DA_tophits <- read_csv(paste0(data_path, "MD_raw_files/", "MD_significant_snps_DA_2022-02-11.csv")) %>%  # 668
                      select(-chrom, -pos, SNP = rsid)
md_gwas_NDA_tophits <- read_csv(paste0(data_path, "MD_raw_files/", "MD_significant_snps_NDA_2022-02-11.csv")) %>% # 670
                      select(-chrom, -pos, SNP = rsid)
md_gwas_PD_tophits <- read_csv(paste0(data_path, "MD_raw_files/", "MD_significant_snps_PD_2022-02-11.csv")) %>%  # 484
                      select(-chrom, -pos, SNP = rsid)

 
length(intersect(md_gwas_DA_tophits$SNP , da_new$SNP)) # 26 # OK
length(intersect(md_gwas_NDA_tophits$SNP , nda_new$SNP)) #16
length(intersect(md_gwas_PD_tophits$SNP , pd_new$SNP)) # 16

length(intersect(md_gwas_DA_tophits$SNP , da_old$SNP)) # 16  # OK
length(intersect(md_gwas_NDA_tophits$SNP , nda_old$SNP)) #11
length(intersect(md_gwas_PD_tophits$SNP , pd_old$SNP)) # 10






full_join(
  da_old %>%  dplyr::select(SNP, old_beta.exposure = beta.exposure, old_pval = pval.exposure),
  da_new %>%  dplyr::select(SNP, new_beta.exposure = beta.exposure, new_pval = pval.exposure),
  by ='SNP') %>% mutate(prev = ifelse(SNP %in% prev_reported, T, F))  %>% View()




md_gwas_DA_tophits <- read_csv(paste0(data_path, "MD_raw_files/", "MD_significant_snps_DA_2022-02-11.csv")) %>% 
                      dplyr::select(-chrom, -pos, SNP = rsid)


prev_reported <- c(
"rs11205277", "rs11205303", 
"rs12468790", "rs4849864", 
"rs17625845", "rs10034692", 
"rs149689338", "rs71219402", 
"rs186749", "rs335143", 
"rs335160", "rs9485370", 
"rs4897108", "rs12665607", 
"rs60705924", "rs7816345", 
"rs10086016", "rs10995190", 
"rs10995181", "rs2089176", 
"rs3817198", "rs703556", 
"rs5800526", "rs1265507", 
"rs9302903", "rs7289126", 
"rs17001868", "rs73169057", 
"rs6001984")

md_gwas_DA_tophits %>% mutate(prev = ifelse(SNP %in% prev_reported, T, F)) %>% View()

```



# Plots

## NB need to rethink what we want this plot to look like (include all BC maybe?)


## MD from shared data

```{r message=F}
current_trait_category <- "md_wo_outliers"

dat_all<-tibble()
for (bc_data in bcac_lookup$trait_file_name[-10]){
  dat <- read_tsv(paste0(results_path, current_trait_category,
           "/","merged_mr_mediators_", current_trait_category,"-to-BCAC_", bc_data,".tsv")) 
  dat_all<-bind_rows(dat_all,dat)
}
dat_all<- dat_all %>%
  mutate(OR_CI =  paste0(round(or,2), " [",round(or_lci95,2) ,":",round(or_uci95,2), "]")) %>%  
  filter(method %in% c("Inverse variance weighted", "Wald ratio")) %>% 
  mutate(outcome= case_when(outcome == 'Breast cancer' & id.outcome == 'ieu-a-1126' ~  'Breast cancer 2017',
                            outcome == 'Breast cancer' & id.outcome != 'ieu-a-1126' ~  'Breast cancer 2020',
                            TRUE ~ outcome)) %>% 
  mutate(exposure = case_when(grepl("non-dense", exposure, ignore.case = T) ~ 'Non-dense area',
                             grepl("Percent", exposure) ~ 'Percent density', 
                             TRUE ~ 'Dense area')) 


dat_all %>% kable_it()

# rearrange to be in the required order
dat_all<-arrange(dat_all, exposure) %>% mutate(exposure=as.factor(exposure))
dat_all$exposure <- forcats::fct_inorder(dat_all$exposure) %>% forcats::fct_rev() 

pal<-(c(unname(yarrr::piratepal("pony"))))[c(1,8,5)]
p<-ggplot(dat_all, aes(y=exposure, x=or, label=outcome, colour=exposure, shape=method)) +
  geom_errorbarh(aes(xmin=or_lci95, xmax=or_uci95), height=.3) +
  geom_point(size=2)+
  scale_color_manual(values=pal)+
  scale_shape_manual(values = c(19,20)) +
  geom_vline(xintercept=1, linetype='longdash') +
  geom_text(aes(label=OR_CI),hjust=-0.1, vjust=-0.6, size =2.5, color = 'darkgrey')+
  theme_minimal_hgrid(10, rel_small = 1) +
  facet_wrap(~outcome, ncol=1)+
  labs(color = "",y = "", x = "Odds ratio",
       title= paste0("Univariate MR results for ", gsub("_", " ",current_trait_category) ,", 95% CI") )+
  theme(legend.position = "none", plot.title.position  = "plot")

ggsave(paste0("figures/mediators_",current_trait_category ,"-to_BCAC_", bc_data,"_IVW.png"),
       plot=p, #scale=1, 
       width=10, height=5,
       units=c("cm"), dpi=200, limitsize=F)

```


```{r}
### try with adult BMI adjusted data --- ignore this block for basic results

dat_all2 <- read_tsv( paste0(results_path, current_trait_category, "/mvmr/merged/merged_mvmr_adultBMI-",current_trait_category,"-to-BCAC.tsv")) %>% 
  filter(exposure != "Adult BMI") %>% 
   filter(outcome != "BRCA1_TN") %>% 
  select(exposure, outcome, or, or_lci95, or_uci95) %>% 
  mutate(outcome = case_when(outcome =="Breast cancer (new)" ~ "BCAC 2020",
                             outcome =="Breast cancer" ~ "BCAC 2017",
                             outcome =="ER+ breast cancer" ~ "ER+",
                             outcome =="ER- breast cancer" ~ "ER-",
                                           outcome =="Luminal A"    ~ "Luminal A",   
                                           outcome =="Luminal B, HER2+"   ~ "Luminal B1",  
                                           outcome =="Luminal B, HER2-" ~ "Luminal B2" ,
                                           outcome =="HER2-enriched"  ~ "HER2-enriched" ,
                                           outcome =="TN Basal"  ~ "TNBC" )) %>% 
   mutate(outcome = factor(outcome, 
                          levels = c("BCAC 2017","BCAC 2020",
                                     "ER+", "ER-",
                                     "Luminal A", "Luminal B1", "Luminal B2", 
                                      "HER2-enriched", "TNBC" )),
         outcome = factor(outcome, levels = rev(levels(outcome)))) %>% 
   mutate(exposure = factor(exposure, levels= rev(c("Dense area", "Non-dense area", "Percent density")))) %>% 
   mutate(effect_direction = ifelse(or_lci95 > 1 & or_uci95 >= 1, 'ok',
                              ifelse(or_lci95 < 1 & or_uci95 <= 1, 'ok', 'overlaps null'))) 
  
```




```{r}
# other plot version
dat_all2 <- dat_all %>% select(exposure, outcome, or, or_lci95, or_uci95, OR_CI) %>% 
  mutate(outcome = case_when(outcome =="Breast cancer 2020" ~ "BCAC 2020",
                             outcome =="Breast cancer 2017" ~ "BCAC 2017",
                             outcome =="ER+ Breast cancer" ~ "ER+",
                             outcome =="ER- Breast cancer" ~ "ER-",
                                           outcome =="Luminal A"    ~ "Luminal A",   
                                           outcome =="Luminal B"   ~ "Luminal B1",  
                                           outcome =="Luminal B-HER2 negative" ~ "Luminal B2" ,
                                           outcome =="HER2 enriched"  ~ "HER2-enriched" ,
                                           outcome =="TNBC Basal-like"  ~ "TNBC" )) %>% 
   mutate(outcome = factor(outcome, 
                          levels = c("BCAC 2017","BCAC 2020",
                                     "ER+", "ER-",
                                     "Luminal A", "Luminal B1", "Luminal B2", 
                                      "HER2-enriched", "TNBC" )),
         outcome = factor(outcome, levels = rev(levels(outcome)))) %>% 
   mutate(effect_direction = ifelse(or_lci95 > 1 & or_uci95 >= 1, 'ok',
                              ifelse(or_lci95 < 1 & or_uci95 <= 1, 'ok', 'overlaps null'))) 

pal<-(c(unname(yarrr::piratepal("pony"))))
pal[6:7]<-c('darkgrey', "#FFEA5E")
p<-ggplot(dat_all2,
           aes(y=exposure, x=or,  colour=outcome, shape = effect_direction)) +
  geom_point(size=3, 
             position = ggstance::position_dodgev(height = 0.7))+
  geom_errorbarh(aes(xmin=or_lci95, xmax=or_uci95), height=.1, 
            position = ggstance::position_dodgev(height = 0.7)) +
  scale_x_continuous(breaks=seq(0.5,3,0.5))+

  theme_minimal_vgrid(11)+
  geom_vline(xintercept=1, linetype='longdash') +
  scale_color_manual(values=pal)+
  scale_shape_manual(values=c(16,1))+
  theme(strip.text = element_text(face = 'bold'),
        strip.text.y = element_text(face = 'bold'),
        panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_line(),
        )+
  panel_border()+
  labs(color = "",y = "", x = "OR", shape="")+
  theme(legend.position = "right", legend.direction = "vertical", 
        plot.title.position = "plot")+
  guides(colour = guide_legend(reverse = TRUE), shape="none")




```


```{r}

# same but using ggforestplot
dat_all3 <- dat_all %>% select(exposure, outcome, b, se, pval) %>% 
  mutate(outcome = case_when(outcome =="Breast cancer 2020" ~ "BCAC 2020",
                             outcome =="Breast cancer 2017" ~ "BCAC 2017",
                             outcome =="ER+ Breast cancer" ~ "ER+ Breast cancer",
                             outcome =="ER- Breast cancer" ~ "ER- Breast cancer",
                             outcome =="Luminal A"    ~ "Luminal A",   
                             outcome =="Luminal B"   ~ "Luminal B1",  
                             outcome =="Luminal B-HER2 negative" ~ "Luminal B2" ,
                             outcome =="HER2 enriched"  ~ "HER2-enriched" ,
                             outcome =="TNBC Basal-like"  ~ "TNBC" )) %>% 
  mutate(outcome = factor(outcome, 
                          levels = c("BCAC 2017","BCAC 2020",
                                     "ER+ Breast cancer","Luminal A", "Luminal B1", "Luminal B2", 
                                     "ER- Breast cancer", "HER2-enriched", "TNBC" )),
         outcome = factor(outcome, levels = rev(levels(outcome)))) %>% 
  rename(name=exposure, trait=outcome)


ggforestplot::forestplot(
  df = dat_all3,
  estimate = b,
  pvalue = pval,
  logodds = F,
  xlab = "OR",
  title = "title",
  colour = trait
)

```







```{r}
###UNIVARIBALE --- md subtypes (not part of this project!)

all.files <- list.files(path = paste0(results_path, "md_traits_sub_run_prev/"), pattern = "merged_mr_mediators_*", full.names = T)
l <- lapply(all.files, read_tsv)

dat<-
  bind_rows(l) %>% 
  filter(method %in% c("Inverse variance weighted")) %>% 
  select(-id.outcome, -method) %>% 
  mutate(OR_CI =  paste0(round(or,2), " [",round(or_lci95,2) ,":",round(or_uci95,2), "]")) %>%   mutate(md_type = case_when(grepl("non-dense", exposure) ~ 'Non-dense',
                             grepl("Percent", exposure) ~ 'Per cent', 
                             TRUE ~ 'Dense')) %>% 
  select(exposure,md_type, outcome, OR_CI, everything()) %>% 
  filter(outcome != 'CIMBA_BRCA1_BCAC_TN')


dat<- dat %>% mutate(outcome = case_when(
               outcome == "Breast cancer" ~ "BCAC_full" ,                   
               outcome == "ER+ Breast cancer" ~ "BCAC_ER+",               
               outcome == "ER- Breast cancer" ~ "BCAC_ER-",               
               outcome == "CIMBA_BRCA1_BCAC_TN" ~ "BCAC_CIMBA_BRCA1_TN" ,                
               outcome == "Breast cancer (overall BCAC 2020)" ~ "BCAC_full_new",
               outcome == "HER2 enriched" ~ "BCAC_HER2_enriched" ,                   
               outcome == "Luminal A" ~ "BCAC_Luminal_A",                       
               outcome == "Luminal B" ~ "BCAC_Luminal_B",                       
               outcome == "Luminal B-HER2 negative" ~ "BCAC_Luminal_B-HER2_negative",         
               outcome == "TNBC Basal-like" ~ "BCAC_TNBC_Basal-like",
               TRUE ~ "x")) %>% 
  mutate(outcome = factor(outcome, levels = c('BCAC_full', "BCAC_full_new", 
        "BCAC_ER-","BCAC_ER+","BCAC_HER2_enriched" , "BCAC_Luminal_A",
        "BCAC_Luminal_B","BCAC_Luminal_B-HER2_negative",  "BCAC_TNBC_Basal-like" )) ) 

dat %>% kable_it()

dat %>% write_csv(paste0(results_path, "md_traits/merged_all_MD_BCAC.tsv"))


# rearrange to be in the required order
dat<-dat %>% mutate(md_type=as.factor(md_type))
dat$md_type <- forcats::fct_inorder(dat$md_type) %>% forcats::fct_rev() 

pal <- wes_palette("Zissou1")[c(1,3,5)]
#dat$mr <- forcats::fct_rev(dat$mr) 
p2<-ggplot(dat, aes(y=md_type, x=or, label=outcome, colour=exposure)) +
  geom_errorbarh(aes(xmin=or_lci95, xmax=or_uci95), height=.3) +
  geom_point(size=2)+
  geom_text(aes(label=OR_CI),hjust=-0.1, vjust=-0.6, size =2.3, color = 'darkgrey')+
  scale_color_manual(values=pal)+
  #scale_shape_manual(values = c(16,20, 5)) +
  geom_vline(xintercept=1, linetype='longdash') +
  theme_minimal_hgrid(9, rel_small = 1) +
  facet_wrap(~outcome, ncol=1)+
  labs(color = "",y = "", x = "Odds ratio",
       title= paste0("        Univariable MR results --- old") )+
   #xlim(0.3, 2.1)+
  theme(legend.position = "none", panel.grid.major.x = element_line())


```

