---
title: "Univarite MR of MD to BC"
author: "Marina Vabistsevits"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(data.table)
library(vroom)

library(tidyr)
library(purrr)
library(tibble)
library(dplyr)

library(TwoSampleMR)
library(ggplot2)
library(cowplot)
library(wesanderson)
```

```{r message=F}
# set path for pre-calculated data, outside the code repo
# `local` / `remote` (reading data from RDSF)
currently_working_env = "local"
source("set_paths.R")
set_paths(currently_working_env)

# metafile
data_lookup<-read_csv(paste0("metadata/data_lookup.csv")) 
bcac_lookup<-read_csv(paste0("metadata/data_lookup_BCAC.csv")) %>% filter(!grepl("BRCA1", trait))

# load functions
source("functions.R")
```


```{r}
# specify group to process if data is in textfiles
source = "textfiles"
current_trait_category <- "md_unadj"
mediators <- data_lookup %>% filter(trait_category == current_trait_category) %>% filter(!is.na(full_data)) %>%  pull(tophits_data)
```


## Reading in / extracting instruments
```{r}
if (source == "textfiles"){
  
    data_list <- lapply(paste0(data_path_tophits, mediators), fread)
    
} else if (source == "mrbase"){

  data_list <- list()
  for (i in 1:length(mediators)){
    instruments <- extract_instruments(mediators[i])
    if (is.null(instruments)){ stop(paste0("No instruments found for ", mediators[i]))} # if no SNPs returned
    data_list[[i]] <- clump_data(instruments)
    data_list[[i]]$exposure <- data_lookup %>% filter(mrbase.id==mediators[i]) %>% pull(trait)
  }
}
```



```{r}
# This for loop will iterate over all breast cancer outcomes and do all steps of MR

for (i in 1:length(bcac_lookup$trait)){

  if (!is.na(bcac_lookup$mr.base.id[i])){
    outcome_source = 'outcome_mrbase'
    outcome_name = bcac_lookup$mr.base.id[i]
    print(paste0( "Testing all mediators against breast cancer data: ", outcome_name))
    breast_cancer_data <- outcome_name
  } else {
    outcome_source = 'outcome_textfile'
    outcome_name = bcac_lookup$full_data[i]
    print(paste0( "Testing all mediators against breast cancer data: ", outcome_name))
    # read in the outcome file
    breast_cancer_data  <- vroom(paste0(data_path_gwas, outcome_name)) 
  }
  outcome_trait_name = bcac_lookup$trait_file_name[i]
  outcome_sample_size =  bcac_lookup$sample.size[i]
  outcome_ncase = bcac_lookup$ncase[i]
  outcome_ncontrol = bcac_lookup$ncontrol[i]

  outcomes <- lapply(data_list, extract_outcome_data_custom, breast_cancer_data, outcome_source)
  
  # check how many SNPs are present in the outcome
  for (i in 1:length(data_list)){
    print(unique(data_list[[i]]$exposure))
    print(paste0("SNPs in exposure: ", dim(data_list[[i]])[1]))
    print(paste0("SNPs matches outcome: ", dim(outcomes[[i]])[1]))
  }
  
  # Harmonise each exposure to the matched outcome SNPs
  harmonise_l <- list()
  for (i in 1:length(data_list)){
     harmonise_l[[i]] <- harmonise_data(exposure_dat = data_list[[i]], 
                                        outcome_dat = outcomes[[i]])
  }
  
  steiger_l <- list()
  for (i in 1:length(data_list)){
     steiger_l[[i]] <- calc_steiger(harmonise_l[[i]], 
                                    exposure_ss = 24192,
                                    outcome_ss = outcome_sample_size, 
                                    outcome_ncase = outcome_ncase,
                                    outcome_ncontrol = outcome_ncase)$summary
  }
  
  # Pleiotropy and Heterogeneity
  sensitivity_l <- list()
  for (i in 1:length(harmonise_l)){
    # don't try it one 1-SNP cases
    if (dim(harmonise_l[[i]])[1] != 1){
    sensitivity_l[[i]] <- full_join(
                          mr_pleiotropy_test(harmonise_l[[i]]),
                          mr_heterogeneity(harmonise_l[[i]], method_list=c("mr_egger_regression", "mr_ivw"))
                          )
    }
  }   
    
  # perform MR
  mr_l <- list()
  for (i in 1:length(harmonise_l)){
    mr_l[[i]] <- mr(harmonise_l[[i]],  method_list=c('mr_ivw','mr_egger_regression','mr_weighted_median', 'mr_wald_ratio') ) 
  }
  
  
  ## Tidy up results 
  #  - Split outcome names
  #  - Generate odds ratios with 95% confidence intervals
    
  tidy_result_l <- list()
  for (i in 1:length(mr_l)){
    tidy_result_l[[i]] <- mr_l[[i]] %>%
                          split_outcome() %>% 
                          split_exposure() %>% 
                          separate(outcome, "outcome", sep="[(]") %>% 
                          generate_odds_ratios()
  }
  
  dat <- tidy_result_l %>%
        reduce(rbind) %>% 
        arrange(method) %>% 
        select(-c("id.exposure")) 
  
  # save full data from MR analyses
  ind_res_dir <- paste0(results_path, current_trait_category, "/")
  ind_res_dir_w_backslash <- gsub(" ", "\\ ", ind_res_dir, fixed=T) # create path vector escaping spaces, otherwise sytem call cant process it
  if(!dir.exists(ind_res_dir)){ system(paste("mkdir -p", ind_res_dir_w_backslash))}
  
  
  write_tsv(dat, paste0(ind_res_dir,"merged_mr_mediators_", current_trait_category,"-to-BCAC_", outcome_trait_name,".tsv"))
  
  
  dat_sensitivity <- sensitivity_l %>%
        reduce(rbind) %>% 
        split_outcome() %>%
        separate(outcome, "outcome", sep="[(]") %>% 
        select(-c("id.exposure")) 
  
  dat_steiger <- steiger_l %>% 
        reduce(rbind) %>% 
        separate(outcome, "outcome", sep="[(]") 
  
  dat_sensitivity <- left_join(dat_sensitivity, dat_steiger, by = c("exposure" = "exposure", "outcome"="outcome"))
  
  
  # save sensitivity analyses results
  write_tsv(dat_sensitivity, paste0(ind_res_dir,"merged_sens_mr_mediators_", current_trait_category,"-to-BCAC_", outcome_trait_name,".tsv"))
  
}
```




