---
title: "MVMR make plots"
author: "Marina Vabistsevits"
date: "01/06/2020"
output: html_document
---

```{r setup, include=FALSE}
library(cowplot)
library(data.table)
library(dplyr)
library(ggplot2)
library(readr)
library(tidyr)
library(TwoSampleMR)
library(wesanderson)
knitr::opts_chunk$set(echo = TRUE)








```

```{r message=F}
# set path for pre-calculated data, outside the code repo
# `local` / `remote` (reading data from RDSF)
currently_working_env = "local"
source("set_paths.R")
set_paths(currently_working_env)

# metafile
data_lookup<-read_csv(paste0("metadata/data_lookup.csv")) 
source("functions.R")

```

```{r}
# specify category and palette to use

current_trait_category <- "md_sub"
pal<-c(unname(yarrr::piratepal("pony")))
```

## MVMR analysis 1: childhood BMI + adult BMI -> mediator

```{r message=F}
dat <- read_tsv(paste0(results_path, current_trait_category, 
                       "/mvmr/merged/merged_mvmr_BMIs-", current_trait_category,"-to-BCAC.tsv"))


pal<-c(unname(yarrr::piratepal("pony")))
p2<-ggplot(dat, aes(y=exposure, x=b, label=outcome, shape=exposure, colour=exposure)) +
  geom_errorbarh(aes(xmin=lo_ci, xmax=up_ci), height=0.2) +
  geom_point(size=2)+
  xlim(-1.2,0.5)+
  scale_color_manual(values=pal)+
  scale_shape_manual(values = c(19,20)) +
  geom_vline(xintercept=0, linetype=3,) +
  theme_minimal_hgrid(10, rel_small = 1) +
  facet_wrap(~outcome, ncol=1)+
  labs(color = "",y = "", x = "Beta",
       title= paste0("MVMR results for ", gsub("_", " ",current_trait_category) ,", 95% CI") )+
  theme(legend.position = "none", plot.title.position  = "plot")

ggsave(paste0("figures/BMI-to-",current_trait_category ,"_MVMR.png"),
       plot=p2, scale=2, 
       width=10, height=5,
       units=c("cm"), dpi=200, limitsize=F)

```

```{r}
x<-plot_grid(p, p2, labels = c('', ''), nrow=2) # p is from 02_...Rmd

ggsave(paste0("figures/BMI-to-MD_unimr_mvmr.png"),
       plot=x, scale=1.4, bg="white",
       width=8, height=11,
       units=c("cm"), dpi=300, limitsize=F)
```



## MVMR analysis 2: childhood BMI + mediator -> breast cancer

```{r}
# previous results
dat_BMI <-  read_tsv("/Users/ny19205/OneDrive - University of Bristol/Documents - OneDrive/Mini-project2/early-bmi-breast-cancer-mr/figures/plotting_data/fig4.tsv")

pp<-ggplot(dat_BMI, aes(y=reorder(direct, -or), x=or, label=outcome, colour=text_col)) +
  geom_errorbarh(aes(xmin=or_lci95, xmax=or_uci95), height=.3) +
  geom_point(size=2)+
  geom_vline(xintercept=0.6632422, linetype=2, colour = "steelblue") + # cBMI total effect
  geom_vline(xintercept=1, linetype='longdash') +
  theme_minimal_hgrid(10) +
  scale_color_manual(values=c("tomato",  "steelblue"))+# old
  #scale_color_manual(values=c("tomato",  "orange","steelblue"))+ # with MD
  scale_y_discrete(position = "right")+
  theme(strip.text = element_text(face = 'bold'))+
  facet_grid(~outcome, scale="free", switch="x")+
  labs(color = "",y = "", x = "Odds ratio", subtitle="" )+
  theme(legend.position = "none")


```


```{r message=F}

dat <- read_tsv( paste0(results_path, current_trait_category, "/mvmr/merged/merged_mvmr_earlyBMI-md_sub-to-BCAC.tsv")) %>% 
  mutate(mediator = case_when(mediator=="dense_area" ~ "MD dense area",
                              mediator=="nondense_area" ~ "MD non-dense area",
                              mediator=="percent_density" ~ "MD percent density")) %>% 
  filter(outcome == "Breast cancer") %>% 
  filter(exposure == "Childhood body size") %>% 
  mutate(direct = paste0(exposure, " accounted for ", mediator)) %>% 
  select(direct, outcome, starts_with("or")) %>% 
  mutate(effect = 'direct', text_col="orange")

dat_BMI <- bind_rows(dat_BMI, dat)

# + rerun prev block!

```


```{r}
# read cBMI direct effct after accounting for all MDs
direct_data <- 
  read_tsv( paste0(results_path, current_trait_category, "/mvmr/merged/merged_mvmr_earlyBMI-md_sub-to-BCAC.tsv")) %>% 
  mutate(mediator = case_when(mediator=="dense_area" ~ "MD dense area",
                              mediator=="nondense_area" ~ "MD non-dense area",
                              mediator=="percent_density" ~ "MD percent density")) %>% 
  filter(exposure == "Childhood body size") %>% 
  filter(outcome != "BRCA1_TN") %>% 
  mutate(exposure = paste0(exposure, " accounted for ", mediator)) %>% 
  select(exposure, outcome, starts_with("or", ignore.case = F)) %>% 
  mutate(outcome = case_when(outcome =="Breast cancer" ~ "BCAC 2017",
                             outcome =="Breast cancer (new)" ~ "BCAC 2020",
                             outcome =="ER+ breast cancer" ~ "ER+",
                             outcome =="ER- breast cancer" ~ "ER-",
                                           outcome =="Luminal A"    ~ "Luminal A",   
                                           outcome =="Luminal B, HER2+"   ~ "Luminal B1",  
                                           outcome =="Luminal B, HER2-" ~ "Luminal B2" ,
                                           outcome =="HER2-enriched"  ~ "HER2-enriched" ,
                                           outcome =="TN Basal"  ~ "TNBC" ))


# read total effects of  cBMI on all BC outcomes
total_data<- 
  read_csv(paste0(results_path, "univariableMR_BMI_BCACall.tsv")) %>% 
  filter(exposure == 'Childhood BMI') %>% 
  select(exposure, outcome, starts_with("or", ignore.case = F)) %>% 
  mutate(exposure = "Childhood body size") %>% 
  filter(outcome != "TNBC_CIMBA_BRCA1") %>% 
  mutate(outcome = case_when(outcome =="Breast cancer" ~ "BCAC 2017",
                             outcome =="Breast cancer (overall BCAC 2020)" ~ "BCAC 2020",
                             outcome =="ER+ Breast cancer" ~ "ER+",
                             outcome =="ER- Breast cancer" ~ "ER-",
                                           outcome =="Luminal A"    ~ "Luminal A",   
                                           outcome =="Luminal B"   ~ "Luminal B1",  
                                           outcome =="Luminal B-HER2 negative" ~ "Luminal B2" ,
                                           outcome =="HER2 enriched"  ~ "HER2-enriched" ,
                                           outcome =="TNBC Basal-like"  ~ "TNBC" ))
  
              
all_data <- bind_rows(total_data, direct_data) %>% 
   mutate(outcome = factor(outcome, levels = c("BCAC 2017","BCAC 2020",
                                     "ER+", "ER-",
                                     "Luminal A", "Luminal B1", "Luminal B2", 
                                      "HER2-enriched", "TNBC" ))) %>% 
         #outcome = factor(outcome, levels = rev(levels(outcome)))) %>% 
  mutate(effect = ifelse(exposure == "Childhood body size", "total", "direct")) %>% 
  mutate(exposure = factor(exposure, levels= c(
    "Childhood body size",   "Childhood body size accounted for MD dense area",   
    "Childhood body size accounted for MD non-dense area",  "Childhood body size accounted for MD percent density")))

pal = wesanderson::wes_palette("GrandBudapest1")
pal = c('steelblue', pal[c(3,2,1)])
qq<-ggplot(all_data, aes(y=rev(exposure), x=or, label=outcome, colour=exposure)) +
  geom_errorbarh(aes(xmin=or_lci95, xmax=or_uci95), height=.3) +
  geom_point(size=2)+
  geom_vline(xintercept=1, linetype='longdash') +
  theme_minimal_hgrid(10) +
  scale_x_continuous(breaks=seq(0.5,1.1,0.1))+
  scale_color_manual(values=pal)+
  scale_y_discrete(position = "right")+
  theme(strip.text = element_text(face = 'bold'))+
  facet_wrap(outcome ~ ., scale="free_y",  ncol = 1)+
  labs(color = "",y = "", x = "Odds ratio", subtitle="" )+
  theme(legend.position = "bottom",
        legend.direction = "vertical", 
        axis.text.y=element_blank()) #remove y axis labels
  



ggsave(paste0("figures/mvmr_earlyBMI-", current_trait_category, "-to-BCAC_", bc_data, mvmr_method, ".png"),
       plot=p, #scale=1, 
       width=15, height=15,
       #width=10, height=5,
       units=c("cm"), dpi=300, limitsize=F)
```
