---
title: "MVMR analysis of BMI and mediators to BC"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(vroom)

library(tidyr)
library(purrr)
library(tibble)
library(dplyr)

library(TwoSampleMR)
library(MVMR)
```

```{r message=F}
# set path for pre-calculated data, outside the code repo
# `local` / `remote` (reading data from RDSF)
currently_working_env = "local"
source("set_paths.R")
set_paths(currently_working_env)

# metafile
data_lookup<-read_csv(paste0("metadata/data_lookup.csv")) 
#phenocor_matrix<-read_tsv(paste0("metadata/pheno_correlations.tsv")) 
bcac_lookup<-read_csv(paste0("metadata/data_lookup_BCAC.csv")) 

# load functions
source("functions_mvmr.R")
source("functions.R")

```



```{r}
da <- read_tsv(paste0(data_path_tophits, "dense_area_tophits.tsv")) 

da_sub <- da %>% 
          filter(!SNP %in% c( "rs11205303", "rs11684853","rs17625845",
                            "rs6001984"
                         )) # exluding SNPs from other dir cluster


da_gwas <-  vroom("/Users/ny19205/OneDrive - University of Bristol/Documents - OneDrive/Mini-project4/01_Data/GWAS_tidy/dense_area_GWAS_tidy_outcome.txt.gz")


igf <- read_tsv(paste0(data_path_tophits, "igf_tophits.tsv"))

igf_gwas <-  vroom("/Users/ny19205/OneDrive - University of Bristol/Documents - OneDrive/Mini-project4/01_Data/GWAS_tidy/igf_GWAS_tidy_outcome.txt.gz")



```

```{r}
# run_mvmr is defined in testing_mvmr_withadultBMI, uses BCAC 2017 overall

# with da only positive
out1 <- run_mvmr(gwas1=da_gwas, gwas2=igf_gwas, instruments1=da_sub, instruments2 =igf )

# with full da
out2 <- run_mvmr(gwas1=da_gwas, gwas2=igf_gwas, instruments1=da, instruments2 =igf )


```

