---
title: "supl data collect"
author: "Marina Vabistsevits"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(data.table)
library(vroom)

library(tidyr)
library(purrr)
library(tibble)
library(dplyr)
library(writexl)
library(readxl)

```

```{r}
# set path for pre-calculated data, outside the code repo
# `local` / `remote` (reading data from RDSF)
currently_working_env = "local"
source("../set_paths.R")
set_paths(currently_working_env)

# metafile
data_lookup<-read_csv(paste0("../metadata/data_lookup.csv")) 

# load functions
source("../functions.R")
```

# Collecting univarible MR results
```{r}
# unadjusted 

# bmi -> md
current_trait_category <- "md" 
bmi_to_md <-      read_tsv(paste0(results_path, current_trait_category, "/merged_mr_BMI-to-",current_trait_category,".tsv")) %>% 
                  select(-starts_with("or")) %>% select(exposure, outcome, everything())
bmi_to_md_sens <- read_tsv(paste0(results_path, current_trait_category, "/merged_sens_mr_BMI-to-",current_trait_category,".tsv"))


# md -> bc
ind_res_dir <- paste0(results_path, current_trait_category)
all.files_mr <- list.files(path = ind_res_dir, pattern = "merged_mr_mediators_*", full.names = T)

l <- lapply(all.files_mr, read_tsv)
md_to_bc <- l %>% reduce(rbind) %>% 
  filter(!grepl("BRCA", outcome)) %>% 
 mutate(outcome = case_when(outcome =="Breast cancer" ~ "BCAC 2020",
                             outcome =="ER+ Breast cancer" ~ "ER+ Breast cancer",
                             outcome =="ER- Breast cancer" ~ "ER- Breast cancer",
                             outcome =="Luminal A"    ~ "Luminal A",   
                             outcome =="Luminal B"   ~ "Luminal B1",  
                             outcome =="Luminal B-HER2 negative" ~ "Luminal B2" ,
                             outcome =="HER2 enriched"  ~ "HER2-enriched" ,
                             outcome =="TNBC Basal-like"  ~ "TNBC" )) %>% 
  mutate(outcome = ifelse(id.outcome == 'ieu-a-1126', "BCAC 2017", outcome)) %>% 
  select(exposure, outcome, method, nsnp, or, or_lci95, or_uci95, pval, b, se) %>% 
  arrange(outcome, exposure) %>% 
  mutate(pval_0.05 = ifelse(pval < 0.051, 1, 0))


ind_res_dir <- paste0(results_path, current_trait_category)
all.files_mr <- list.files(path = ind_res_dir, pattern = "merged_sens_mr_mediators_*", full.names = T)

l <- lapply(all.files_mr, read_tsv)
md_to_bc_sens <- l %>% reduce(bind_rows) %>% 
 filter(!grepl("BRCA", outcome)) %>% 
 mutate(outcome = case_when(outcome =="Breast cancer" ~ "BCAC 2020",# bcac 2017 is manually added to file
                             outcome =="ER+ Breast cancer" ~ "ER+ Breast cancer",
                             outcome =="ER- Breast cancer" ~ "ER- Breast cancer",
                             outcome =="Luminal A"    ~ "Luminal A",   
                             outcome =="Luminal B"   ~ "Luminal B1",  
                             outcome =="Luminal B-HER2 negative" ~ "Luminal B2" ,
                             outcome =="HER2 enriched"  ~ "HER2-enriched" ,
                             outcome =="TNBC Basal-like"  ~ "TNBC" ,
                             TRUE ~ outcome)) %>% 
  mutate(outcome = ifelse(id.outcome == 'ieu-a-1126', "BCAC 2017", outcome)) %>% 
  select(exposure, outcome, everything()) %>% 
  arrange(outcome, exposure)


# aaM -> md
aam_to_md <-  read_tsv(paste0(results_path, current_trait_category, "/", current_trait_category, "_w_traits_biMR_results.tsv")) %>% 
              filter(exposure == "Age when periods started (menarche)") %>% 
              mutate(exposure = ifelse(exposure == "Age when periods started (menarche)", "Age at menarche", exposure)) %>%
              select(-starts_with("or"), -id.outcome, -dir) %>% 
              select(id.exposure, exposure, outcome, method, nsnp, pval,se, everything()) %>% 
              arrange(outcome, exposure)

aam_to_md_sens <-  read_tsv(paste0(results_path, current_trait_category, "/", current_trait_category, "_w_traits_biMR_results_sens.tsv")) %>% 
              filter(exposure == "Age when periods started (menarche) || id:ukb-b-3768") %>% 
              mutate(exposure = ifelse(exposure == "Age when periods started (menarche) || id:ukb-b-3768", "Age at menarche", exposure)) %>% 
              select(exposure, outcome, everything(), -dir)


### MVMR

# aaM +cbmi -> MD 
mvmr_aaM_cbmi_to_md <- read_tsv(paste0(results_path,"md_w_traits/","mvmr_results_w_cBMI_",current_trait_category,".tsv")) %>% 
                        select(-starts_with("or")) %>% 
                        select(exposure, outcome,  nsnp, pval, se, everything()) %>% 
                        mutate(exposure = ifelse(exposure =="age_at_menarche_ukb",  "Age at menarche", exposure)) %>% 
                        mutate(pair = ifelse(pair =="age_at_menarche_ukb",  "Age at menarche", pair)) %>% 
                        filter(pair == "Age at menarche")

mvmr_aaM_cbmi_to_md_sens <- read_tsv( paste0(results_path,"md_w_traits/","mvmr_sens_results_w_cBMI_",current_trait_category,".tsv")) %>% 
                            rename("Age at menarche (Fst)" =  "age_at_menarche_ukb (Fst)") %>% select(-c("IGF (Fst)"))

                            

# cbmi+abmi -> md
mvmr_BMIs_to_md <- read_tsv(paste0(results_path, current_trait_category, "/mvmr/merged/merged_mvmr_BMIs-",current_trait_category,"-to-BCAC.tsv")) %>%
                   select(-starts_with("or"))
mvmr_BMIs_to_md_sens <- read_tsv(paste0(results_path, current_trait_category, "/mvmr/merged/merged_sens_mvmr_sens_BMIs-",current_trait_category,"-to-BCAC.tsv"))%>%            select(outcome_trait=trait, everything())


# cbmi + md -> bc
mvmr_cBMI_md_to_bc <- read_tsv(paste0(results_path, current_trait_category, "/mvmr/merged/merged_mvmr_earlyBMI-",current_trait_category,"-to-BCAC.tsv")) %>% 
  filter(!grepl("BRCA", outcome)) %>% 
  mutate(outcome = case_when(outcome =="Breast cancer (new)" ~ "BCAC 2020",
                             outcome =="Breast cancer" ~ "BCAC 2017",
                             outcome =="ER+ Breast cancer" ~ "ER+ Breast cancer",
                             outcome =="ER- Breast cancer" ~ "ER- Breast cancer",
                             outcome =="Luminal A"    ~ "Luminal A",   
                             outcome =="Luminal B, HER2+"   ~ "Luminal B1",  
                             outcome =="Luminal B, HER2-" ~ "Luminal B2" ,
                             outcome =="HER2 enriched"  ~ "HER2-enriched" ,
                             outcome =="TN Basal"  ~ "TNBC" ,
                             TRUE ~ outcome)) %>% 
  select(exposure, outcome, nsnp, or, or_lci95, or_uci95, pval,b,se ,mediator) %>% 
  arrange(mediator, outcome, exposure) %>% 
  mutate(pval_0.05 = ifelse(pval < 0.051, 1, 0)) 

outs <- rep(unique(mvmr_cBMI_md_to_bc$outcome),3)

mvmr_cBMI_md_to_bc_sens <- read_tsv(paste0(results_path, current_trait_category, "/mvmr/merged/merged_sens_mvmr_sens_earlyBMI-",current_trait_category,"-to-BCAC.tsv")) %>% 
                          select(-Qstat, -Qpval, everything(), Qstat, Qpval)
mvmr_cBMI_md_to_bc_sens$outcome <- outs

```


```{r}
# only for unadjusted data


# total cBMI -> BC results

total_data<- 
  read_csv(paste0(results_path, "univariableMR_BMI_BCACall.tsv")) %>% 
  filter(exposure == 'Childhood BMI') %>% 
  select(-OR_CI) %>% 
  mutate(exposure = "Childhood body size") %>% 
  filter(!grepl("BRCA", outcome)) %>% 
  mutate(outcome = case_when(outcome =="Breast cancer (overall BCAC 2020)" ~ "BCAC 2020",
                             outcome =="Breast cancer" ~ "BCAC 2017",
                             outcome =="ER+ Breast cancer" ~ "ER+ Breast cancer",
                             outcome =="ER- Breast cancer" ~ "ER- Breast cancer",
                             outcome =="Luminal A"    ~ "Luminal A",   
                             outcome =="Luminal B"   ~ "Luminal B1",  
                             outcome =="Luminal B-HER2 negative" ~ "Luminal B2" ,
                             outcome =="HER2 enriched"  ~ "HER2-enriched" ,
                             outcome =="TNBC Basal-like"  ~ "TNBC" ,
                             TRUE ~ outcome))



# MR-presso results

presso_da <- read_tsv(paste0(results_path, current_trait_category, "/presso_radial/", "DA_unadj" ,"_presso_results.tsv"))
presso_nda <- read_tsv(paste0(results_path, current_trait_category, "/presso_radial/", "NDA_unadj" ,"_presso_results.tsv"))
presso_pd <- read_tsv(paste0(results_path, current_trait_category, "/presso_radial/", "PD_unadj" ,"_presso_results.tsv"))
mrpresso = bind_rows(presso_da, presso_nda, presso_pd)
mrpresso$analysis <- "MR-PRESSO"


# Radial 
radial_da <- read_tsv(paste0(results_path, current_trait_category, "/presso_radial/", "DA_unadj", "_radial_supl.tsv"))
radial_nda <- read_tsv(paste0(results_path, current_trait_category, "/presso_radial/", "NDA_unadj", "_radial_supl.tsv"))
radial_pd <- read_tsv(paste0(results_path, current_trait_category, "/presso_radial/", "PD_unadj", "_radial_supl.tsv"))
radial <- bind_rows(radial_da, radial_nda, radial_pd)
radial$analysis <- "Radial-MR"
# cluster 
cluster_da <- read_tsv(paste0(results_path,"MRClust_results/","DA_unadj" ,"_cluster_supl.tsv"))
cluster_nda <- read_tsv(paste0(results_path,"MRClust_results/","NDA_unadj" ,"_cluster_supl.tsv"))
cluster_pd <- read_tsv(paste0(results_path,"MRClust_results/","PD_unadj" ,"_cluster_supl.tsv"))
cluster <- bind_rows(cluster_da, cluster_nda, cluster_pd)
cluster$analysis <- "MR-Clust"


# phewas

phewas_da <- read_tsv(paste0(results_path,"phewas/","DA_unadj" ,"_phewas_results.tsv")) %>% mutate(analysis = "PheWAS DA") %>% select(analysis, everything())
phewas_nda <- read_tsv(paste0(results_path,"phewas/","NDA_unadj" ,"_phewas_results.tsv")) %>% mutate(analysis = "PheWAS NDA") %>% select(analysis, everything())
phewas_pd <- read_tsv(paste0(results_path,"phewas/","PD_unadj" ,"_phewas_results.tsv")) %>% mutate(analysis = "PheWAS PD") %>% select(analysis, everything())


```


```{r}

if (current_trait_category == "md_unadj" ) {
  guide_table <- read_xlsx(paste0(results_path, "guide_table_",current_trait_category,".xlsx"))
  
  #### write to xls
  sheets <- list("Guide" = guide_table,
                 "S3" = bmi_to_md, 
                 "S4" = bmi_to_md_sens,
                 "S5"=mvmr_BMIs_to_md, 
                 "S6"=mvmr_BMIs_to_md_sens, 
                 "S7" = aam_to_md, # cmi total is in 1
                 "S8" = aam_to_md_sens,
                 "S9" = mvmr_aaM_cbmi_to_md,
                 "S10" = mvmr_aaM_cbmi_to_md_sens,
                 "S11" = md_to_bc,
                 "S12" = md_to_bc_sens,
                 "S13"= mvmr_cBMI_md_to_bc,
                 "S14" = mvmr_cBMI_md_to_bc_sens,
                 "S15" = total_data, 
                 "S16" = mrpresso,
                 "S17" = radial,
                 "S18" = cluster,
                 "S19" = phewas_da,
                 "S20" = phewas_nda,
                 "S21" = phewas_pd
                 
                 ) 
  write_xlsx(sheets, paste0(results_path, "all_results_",current_trait_category,".xlsx"))
}

```


```{r}
if (current_trait_category == "md" ) {
  guide_table <- read_xlsx(paste0(results_path, "guide_table_",current_trait_category,".xlsx"))
  
  #### write to xls
  sheets <- list("Guide" = guide_table,
                 "S28" = bmi_to_md, 
                 "S29" = bmi_to_md_sens,
                 "S30"=mvmr_BMIs_to_md, 
                 "S31"=mvmr_BMIs_to_md_sens, 
                 "S32" = aam_to_md, # cmi total is in 1
                 "S33" = aam_to_md_sens,
                 "S34" = mvmr_aaM_cbmi_to_md,
                 "S35" = mvmr_aaM_cbmi_to_md_sens, # manually remove IGF rows
                 "S36" = md_to_bc,
                 "S37" = md_to_bc_sens,
                 "S38"= mvmr_cBMI_md_to_bc,
                 "S39" = mvmr_cBMI_md_to_bc_sens
                 
                 ) 
  write_xlsx(sheets, paste0(results_path, "all_results_",current_trait_category,".xlsx"))
}

```


```{r}
# pathway analysis stuff
current_trait_category <- "md_unadj" 

# SNP to gene
genes_da<-read_tsv(paste0(results_path, "SNP_to_gene_to_pathway/", "DA_unadj", "_snps_clusters_gene_annotation.tsv")) 
genes_nda<-read_tsv(paste0(results_path, "SNP_to_gene_to_pathway/", "NDA_unadj", "_snps_clusters_gene_annotation.tsv")) 
genes_pd<-read_tsv(paste0(results_path, "SNP_to_gene_to_pathway/", "PD_unadj", "_snps_clusters_gene_annotation.tsv")) 

# gene to pathways
pathways_da <- read_tsv(paste0(results_path, "SNP_to_gene_to_pathway/", "DA_unadj", "_pathways_by_clusters_tidy.tsv")) 
pathways_nda <- read_tsv(paste0(results_path, "SNP_to_gene_to_pathway/", "NDA_unadj", "_pathways_by_clusters_tidy.tsv")) 
pathways_pd <- read_tsv(paste0(results_path, "SNP_to_gene_to_pathway/", "PD_unadj", "_pathways_by_clusters_tidy.tsv")) 


#### write to xls
sheets <- list( 'S22 genes_DA' = genes_da,
                'S23 genes_NDA' = genes_nda,
                'S24 genes_PD' = genes_pd,
                'S25 pathways_DA'  = pathways_da ,
                'S26 pathways_NDA' = pathways_nda,
                'S27 pathways_PD'  = pathways_pd )

write_xlsx(sheets, paste0(results_path, "all_results_",current_trait_category,"_genes_pathways.xlsx"))



```


