---
title: "MVMR make plots"
author: "Marina Vabistsevits"
date: "01/06/2020"
output: html_document
---

```{r setup, include=FALSE}
library(cowplot)
library(data.table)
library(dplyr)
library(ggplot2)
library(readr)
library(tidyr)
library(TwoSampleMR)
library(wesanderson)
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=F}
# set path for pre-calculated data, outside the code repo
# `local` / `remote` (reading data from RDSF)
currently_working_env = "local"
source("set_paths.R")
set_paths(currently_working_env)

# metafile
data_lookup<-read_csv(paste0("metadata/data_lookup.csv")) 
source("functions.R")

```

```{r}
# specify category and palette to use

current_trait_category <- "md_unadj"
pal<-c(unname(yarrr::piratepal("pony")))
```



## MVMR analysis with prev mediators: childhood BMI + mediators -> breast cancer

```{r}
# previous results
dat_BMI <-  read_tsv("/Users/ny19205/OneDrive - University of Bristol/Documents - OneDrive/Mini-project2/early-bmi-breast-cancer-mr/figures/plotting_data/fig4.tsv")

pp<-ggplot(dat_BMI, aes(y=reorder(direct, -or), x=or, label=outcome, colour=text_col)) +
  geom_errorbarh(aes(xmin=or_lci95, xmax=or_uci95), height=.3) +
  geom_point(size=2)+
  geom_vline(xintercept=0.6632422, linetype=2, colour = "steelblue") + # cBMI total effect
  geom_vline(xintercept=1, linetype='longdash') +
  theme_minimal_hgrid(10) +
  #scale_color_manual(values=c("tomato",  "steelblue"))+# old
  scale_color_manual(values=c("tomato",  "orange","steelblue"))+ # with MD
  scale_y_discrete(position = "right")+
  theme(strip.text = element_text(face = 'bold'))+
  facet_grid(~outcome, scale="free", switch="x")+
  labs(color = "",y = "", x = "Odds ratio", subtitle="" )+
  theme(legend.position = "none")


dat <- read_tsv( paste0(results_path, current_trait_category, "/mvmr/merged/merged_mvmr_earlyBMI-",current_trait_category,"-to-BCAC.tsv")) %>% 
  mutate(mediator = case_when(grepl("nondense_area", mediator) ~ "MD non-dense area (unadj)",
                              grepl("dense_area", mediator) ~ "MD dense area (unadj)",
                              grepl("percent_density", mediator) ~ "MD percent density (unadj)")) %>% 
  filter(outcome == "Breast cancer") %>% 
  filter(exposure == "Childhood body size") %>% 
  mutate(direct = paste0(exposure, " accounted for ", mediator)) %>% 
  select(direct, outcome, starts_with("or")) %>% 
  mutate(effect = 'direct', text_col="orange")

dat_BMI <- bind_rows(dat_BMI, dat)

# + rerun prev block!

```
