---
title: "Outlier IVW for all subtypes"
author: "Marina Vabistsevits"
date: "`r Sys.Date()`"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(vroom)

library(tidyr)
library(dplyr)

library(TwoSampleMR)
library(RadialMR)
library(ieugwasr)

library(cowplot)
library(ggplot2)
```

```{r message=F}
# set path for pre-calculated data, outside the code repo
# `local` / `remote` (reading data from RDSF)
currently_working_env = "local"
source("../set_paths.R")
set_paths(currently_working_env)

# metafile
data_lookup<-read_csv(paste0("../metadata/data_lookup.csv")) 
bcac_lookup<-read_csv(paste0("../metadata/data_lookup_BCAC.csv")) 

# load functions
source("../functions.R")
```

# Select and load data - one at a time

```{r}

# primary MD unadjusted data

da <- read_tsv(paste0(data_path_tophits, "dense_area_unadj_tophits.tsv")) 
exposure_name <- unique(da$exposure)
exp_code <- "DA_unadj"

if (grepl("unadj", exp_code)){dir <- "md_unadj"}
```

```{r}

# MR


# collect harmonised and single snp res
outcomes_list<- list()
for (i in 1:9 ){ # only local data outcomes
#for (i in 1:length(bcac_lookup$trait)){ # when opengwas starts working again

  if (!is.na(bcac_lookup$mr.base.id[i])){
    outcome_source = 'outcome_mrbase'
    outcome_name = bcac_lookup$mr.base.id[i]
    print(paste0( "reading breast cancer data: ", outcome_name))
    breast_cancer_data <- outcome_name
  } else {
    outcome_source = 'outcome_textfile'
    outcome_name = bcac_lookup$full_data[i]
    print(paste0( "reading breast cancer data: ", outcome_name))
    # read in the outcome file
    breast_cancer_data  <- vroom(paste0(data_path_gwas, outcome_name)) 
  }
  outcome_trait_name = bcac_lookup$trait_file_name[i]
  outcome_sample_size =  bcac_lookup$sample.size[i]
  outcome_ncase = bcac_lookup$ncase[i]
  outcome_ncontrol = bcac_lookup$ncontrol[i]
  
  outcomes_list[[i]] <-  lapply(list(da), extract_outcome_data_custom, breast_cancer_data, outcome_source)[[1]]
  
}
  
  # Harmonise each exposure to the matched outcome SNPs
  harmonise_l <- list()
  for (i in 1:length(outcomes_list)){
     harmonise_l[[i]] <- harmonise_data(exposure_dat = da, 
                                        outcome_dat = outcomes_list[[i]]) %>% 
                         TwoSampleMR::split_outcome() %>% 
                         separate(outcome, sep = "\\(", into = c("outcome", "tmp"), remove = T) %>% 
                         # applies only the relevant one
                        mutate(outcome = case_when(
                                             outcome =="Breast cancer " & id.outcome == 'ieu-a-1126' ~ "Overall BCAC 2017",
                                             outcome =="ER+ Breast cancer " ~ "ER+",
                                             outcome =="ER- Breast cancer " ~ "ER-",
                                              outcome =="Breast cancer " ~ "Overall BCAC 2020",
                                                           outcome =="Luminal A"    ~ "Luminal A",   
                                                           outcome =="Luminal B"   ~ "Luminal B1",  
                                                           outcome =="Luminal B-HER2 negative" ~ "Luminal B2" ,
                                                           outcome =="HER2 enriched"  ~ "HER2-enriched" ,
                                                           outcome =="TNBC Basal-like"  ~ "TNBC" ))
  }
  
  res_single_l <- list()
  for (i in 1:length(harmonise_l)){
    res_single_l[[i]] <- mr_singlesnp(harmonise_l[[i]], 
                                 all_method=c("mr_ivw_mre","mr_egger_regression", "mr_weighted_median"))%>% 
                    mutate(SNP = gsub("Inverse variance weighted (multiplicative random effects)", "IVW (MRE)", SNP, fixed = T)) 
  }


```


```{r}
library(RadialMR)


SNPorder <- read_tsv(paste0(results_path, dir, "/presso_radial/", exp_code,"_radial_supl.tsv")) %>% 
          filter(grepl("rs", SNP)) %>% arrange(-b) %>% pull(SNP) # from main figure

radial_results<-tibble()
plots<- list()

for (i in 1:9 ){ 
  
  # format
  raddat <- format_radial(
    harmonise_l[[i]]$beta.exposure,  harmonise_l[[i]]$beta.outcome,
     harmonise_l[[i]]$se.exposure,  harmonise_l[[i]]$se.outcome, 
     harmonise_l[[i]]$SNP)
  
  # test IVW 
  ivwrad <- ivw_radial(raddat, alpha=0.05/nrow(raddat), weights=3) 
  
  # select outliers
  ivwrad$sortoutliers <- ivwrad$outliers[order(ivwrad$outliers$p.value),]
  ivwrad$sortoutliers$Qsum <- cumsum(ivwrad$sortoutliers$Q_statistic)
  ivwrad$sortoutliers$Qdif <- ivwrad$sortoutliers$Qsum - ivwrad$qstatistic
  
  # mr without outliers
  res_outliers_radial <-  harmonise_l[[i]] %>% 
          filter(!SNP %in% ivwrad$sortoutliers$SNP) %>% 
          mr() %>% 
          filter(method == "Inverse variance weighted") %>% 
          dplyr::rename(p=pval, SNP=method) %>% 
          mutate(SNP = "Outlier corrected - IVW")
  
  res_outliers_radial <- bind_rows(res_single_l[[i]], res_outliers_radial)
  outliers_list = append(ivwrad$sortoutliers$SNP, 'Outlier corrected - IVW')
  
  res_outliers_radial2 <- res_outliers_radial %>% mutate(outcome = unique(harmonise_l[[i]]$outcome)) %>% 
                                                  mutate(SNP = factor(SNP, levels = c(SNPorder, c("All - IVW (MRE)", "All - MR Egger" ,
                                                                                "All - Weighted median", "Outlier corrected - IVW")))) %>% 
                                                  arrange(SNP)
                            
  forest_radial <- mr_forest_plot_outliers(res_outliers_radial,  outliers_list=outliers_list, outliers_colour = "orange", method = "", snp_order = rev(SNPorder) )
  plots[[i]]<- forest_radial
  
  ggsave(plot=forest_radial, 
        height=5, width=6,
        filename=paste0(results_path, dir, "/presso_radial/subtypes_", exp_code,"_snps_outliers_forest_radial_", gsub(" ", "_", unique(harmonise_l[[i]]$outcome)) ,".png"))
  
  # radial supl file
  
  supl <- res_outliers_radial %>% 
    mutate(is_outlier = ifelse(SNP %in% ivwrad$sortoutliers$SNP, T, F)) %>% 
    dplyr::select(-nsnp, -id.exposure)
  
  radial_results<-bind_rows(radial_results, supl)
}  
radial_results<- radial_results %>% 
          TwoSampleMR::generate_odds_ratios() %>% select(-lo_ci, -up_ci) %>% 
           mutate_at(vars(starts_with("or")), funs(ifelse(grepl("rs", SNP), NA, . )))

write_tsv(radial_results, paste0(results_path, dir, "/presso_radial/", exp_code,"_radial_supl_subtypesBC.tsv")) # manually added to Supl data 17


```

```{r}
library(cowplot)

radial_plots <-
  plot_grid(plotlist = plots[c(1,4,2,3,5:9)],
           labels = "auto",
           label_size = 12,
          axis = "t", ncol=2) 

ggsave(plot=radial_plots, 
      height=16, width=8, scale=1, dpi=300, 
      filename=paste0(results_path, dir, "/presso_radial/subtypes_", exp_code,"_snps_outliers_forest_radial_ALL_ordered2.png"))



```


